### ISSUE TITLE
AnimBP variables not updated correctly in some circumstances

### ISSUE THREAD

**Issue by mhomde** [ProjectBorealis/PBSync#17]
So some parameters are updated correctly with the AnimInstance "pulling" data from the character, some however are being "pushed" from the Character class into the animbp when they change (like movement state) This means that if you have any secondary anim instances, for instance layers, they won't have their variables updated correctly. 

Would probably be better if the AnimInstance pulls all information in NativeUpdateAnimation from the Character Class

**Comment by mastercoms** [comment]
Wrong repo? :D

**Comment by mhomde** [comment]
> Wrong repo? :D

Yeah :)  Sorry
